### ISSUE TITLE
four sided figures

### ISSUE THREAD

**Issue by ghost** [rdp1070/PokeMath#6]
there are many four-sided figures that are not squares, and that thus should be counted as acceptable answers to the question about four-sided figures.

This can be fixed either by a) making all those answers correct [eg, testing for rhombus, trapezoid, rectangle, quadrilateral) or b) by changing the question to one about a figure with "four equal sides".

Me, at this point, I'd just add the "equal".

**Comment by ghost** [comment]
oh, I guess "rhombus" still counts there. So, you'd have to add something about right angles too I guess. Or, you could specify it as "regular" (which refers to being equilateral and equi-angular).

Hmm.

**Comment by rdp1070** [comment]
Thanks for the report, I am addressing this in the version I am working on. 
I was going to say regular with equal sides. 
As the monster levels up I was going to ask about 4 sides without equal sides. 
When I push I will close this ticket.

**Comment by mxb9328** [comment]
Changed the wording of the question to ask how many shapes a side has so the answer to both square and rectangle is 4.
